# See this wiki page for more info:
# https://github.com/dylanaraps/neofetch/wiki/Customizing-Info

# [Credits] elysianmyst

print_info() {
    info "\n   \n   \n   \n   \n   \n$(color 13)﹙󰤄﹚" title
    prin "$(color 243)───────────────────────────── ◦"

    info "$(color 11) " distro &
    info "$(color 10)󰌪 " kernel &
    info "$(color  9)󰅟 " uptime &
    info "$(color 12)󱧶 " packages &
    info "$(color 13) " term &
    info "$(color 14)󰞑 " memory &
    info "$(color 15)󰎈 " song &
 
    # Wait for the function to complete
    wait

    prin "$(color 243)───────────────────────────── ◦"
    prin "$(color 11)󰮯　 $(color 9)󰊠　 $(color 10)󰊠　 $(color 11)󰊠　 $(color 12)󰊠　 $(color 13)󰊠　 $(color 14)󰊠　 $(color 15)󰊠"

    # Print colors
    info cols 
}

# Shorten the output of the kernel function.
kernel_shorthand="on"

# -------------- [Basics] --------------

# Distro
distro_shorthand="off"

# Show/Hide OS Architecture.
os_arch="off"

# Uptime
uptime_shorthand="on"

# -------------- [Memory] --------------

# Show memory pecentage in output.
memory_percent="on"

# Change memory output unit.
memory_unit="gib"

# ------------- [Packages] -------------

# Show/Hide Package Manager names.
package_managers="on"

# --------------- [Song] ---------------

# Indentifies music player automatically
music_player="auto"

# Format to display song information.
song_format="%artist% [ %album% ] - %title%"

# Print the Artist, Album and Title on separate lines
song_shorthand="off"

# ----------- [Text Options] -----------
# Format: 'title', '@', 'underline', 'subtitle', 'colon', 'info'

# Text Colors
colors=(7 14 7 6 14 7)

# Toggle bold text
bold="on"

# Info Separator
separator="​"

# ----------- [Color Blocks] -----------
#
# Color block range
block_range=(0 15)

# Toggle color blocks
color_blocks="on"

# Color block width in spaces
block_width=3

# Color block height in lines
block_height=1

# Color Alignment
col_offset="auto"

# ----------- [Ascii Option] -----------

# Distro Icon
ascii_distro="arch_small"

# Ascii Colors
# Values:   'distro', 'num' 'num' 'num' 'num' 'num' 'num'
ascii_colors=(6 7)

# Bold ascii logo
ascii_bold="on"

# --------------- [Miscs] --------------

# Misc Options
stdout="off"
