# -------------------------------
#            Alacritty
# -------------------------------

[general]
import             = [ "~/.config/alacritty/themes/catppuccin-mocha.toml" ]

[window]
decorations        = "None"
padding            = { x = 15, y = 15 }
dimensions         = { columns = 120, lines = 25 }

[font]
size               = 11.5
normal             = { family = "JetBrainsMono Nerd Font", style = "Medium" }
bold               = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic             = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic        = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[cursor]
style              = { shape = "Beam" }
blink_interval     = 500
thickness          = 0.25

[[keyboard.bindings]]
action             = "ScrollLineDown"
key                = "J"
mode               = "~Vi"
mods               = "Control | Shift"

[[keyboard.bindings]]
action             = "ScrollLineUp"
key                = "K"
mode               = "~Vi"
mods               = "Control | Shift"
