import = [ "~/.config/alacritty/themes/gruvbox_dark.toml" ]

[window]
opacity = 0.95
decorations = "none"
decorations_theme_variant = "Dark"

dimensions = { columns = 120, lines = 30 }
padding = {x = 6, y = 8}
class = {instance = "Alacritty", general = "Alacritty"}

[cursor]
blink_interval = 500
unfocused_hollow = true
thickness = 0.27

style = {shape = "Beam"}

[font]
size = 12

normal = {family = "CaskaydiaCove Nerd Font", style = "Medium"}
bold = {family = "CaskaydiaCove Nerd Font", style = "Bold"}
italic = {family = "CaskaydiaCove Nerd Font", style = "Italic"}
