import = [ "~/.config/alacritty/themes/gruvbox_material_dark.toml" ]

[window]
opacity = 1
decorations = "none"
decorations_theme_variant = "Dark"

startup_mode = "Windowed"
dimensions = { columns = 120, lines = 30 }
padding = {x = 8, y = 10}
class = {instance = "Alacritty", general = "Alacritty"}

[cursor]
blink_interval = 500
unfocused_hollow = true
thickness = 0.27

style = {shape = "Beam"}

[font]
size = 13

normal = {family = "CaskaydiaMono Nerd Font", style = "Medium"}
bold = {family = "CaskaydiaMono Nerd Font", style = "Bold"}
italic = {family = "CaskaydiaMono Nerd Font", style = "Italic"}
