# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

format = """
[ ](fg:green)\
$directory\
$git_branch\
$cmd_duration\
$fill\
$git_status\
$line_break\
$character"""

palette = "mocha"
add_newline = true

[fill]
symbol = " "

[directory]
truncation_length = 4
home_symbol       = "~"
read_only         = " 󰉐 "
read_only_style   = "bold sapphire"
style             = "bold subtext1"

[character]
success_symbol       = "[❯](bold blue)"
error_symbol         = "[❯](bold red)"
vimcmd_symbol        = "[❮](bold peach)"
vimcmd_visual_symbol = "[❮](bold sky)"

[cmd_duration]
min_time = 500
style    = "peach"
format   = "• took [$duration]($style)"

[git_branch]
style  = "blue"
format = "󰊤 [$branch]($style) "

[git_status]
ahead      = "[](bold teal) ${count} "
behind     = "[](bold red) ${count} "
staged     = "[](bold green) ${count} "
stashed    = "[󰆧](bold blue) ${count} "
renamed    = "[󰷬](bold peach) ${count} "
deleted    = "[](bold maroon) ${count} "
diverged   = "[](bold peach) ${ahead_count} ${behind_count} "
modified   = "[󰷉](bold mauve) ${count} "
untracked  = "[](bold flamingo) ${count} "
conflicted = "[](bold red) ${count} "
format     = "$staged$modified$renamed$untracked$deleted$conflicted$stashed$ahead_behind"

[palettes.mocha]
rosewater = "#f5e0dc"
flamingo  = "#f2cdcd"
pink      = "#f5c2e7"
mauve     = "#cba6f7"
red       = "#f38ba8"
maroon    = "#eba0ac"
peach     = "#fab387"
yellow    = "#f9e2af"
green     = "#a6e3a1"
teal      = "#94e2d5"
sky       = "#89dceb"
sapphire  = "#74c7ec"
blue      = "#89b4fa"
lavender  = "#b4befe"
text      = "#cdd6f4"
subtext1  = "#bac2de"
subtext0  = "#a6adc8"
overlay2  = "#9399b2"
overlay1  = "#7f849c"
overlay0  = "#6c7086"
surface2  = "#585b70"
surface1  = "#45475a"
surface0  = "#313244"
base      = "#1e1e2e"
mantle    = "#181825"
crust     = "#11111b"
