format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\n$character
"""

add_newline = true

[character]
error_symbol   = "[λ](bold red)"
success_symbol = "[λ](bold green)"
vicmd_symbol   = "[λ](bold yellow)"

[cmd_duration]
style = "bold yellow"
format = "﹙took [$duration]($style)﹚"

[directory]
style     = "bold cyan"
read_only = " "
read_only_style = "bold yellow"

[git_branch]
style = "bold magenta"
format = "[󰊤 $branch]($style) "

[git_status]
ahead      = "[ ${count}](bold blue) "
behind     = "[ ${count}](bold cyan) "
staged     = "[ ${count}](bold green) "
stashed    = "[󱉙 ${count}](bold purple) "
renamed    = "[ ${count}](bold cyan) "
deleted    = "[ ${count}](bold red) "
diverged   = "[ ${ahead_count} ${behind_count}](bold white) "
modified   = "[󱇧 ${count}](bold yellow) "
untracked  = "[ ${count}](bold white) "
conflicted = "[󰉀 ${count}](bold red) "
format     = "($staged$modified$renamed$untracked$deleted$conflicted$stashed$ahead_behind)"
