# ------------------------------------------
#                   Catnap
# ------------------------------------------
# https://github.com/iinsertNameHere/catnap
# ------------------------------------------

# ------------------------------------------
#                Stats & Info 
# ------------------------------------------

[stats]
username  = { icon = " ", name = "user", color = "(RD)" }
hostname  = { icon = " ", name = "hostname", color = "(YW)" }
uptime    = { icon = "󰔚 ", name = "uptime", color = "(BE)" }
distro    = { icon = " ", name = "distro", color = "(GN)" }
kernel    = { icon = " ", name = "kernel", color = "(MA)" }
desktop   = { icon = "󰨇 ", name = "wm", color = "(CN)" }
packages  = { icon = " ", name = "packages", color = "(GN)" }  # WARNING: Resource Intensive
disk_0    = { icon = " ", name = "disk", color = "(BE)" }
memory    = { icon = " ", name = "memory", color = "(YW)" }
cpu       = { icon = " ", name = "cpu", color = "(GN)" }
sep_color = "SEPARATOR"
colors    = { icon = " ", name = "colors", color = "!DT!", symbol = "" }

# terminal  = {icon = " ", name = "term", color = "(RD)"}
# shell     = {icon = " ", name = "shell", color = "(MA)"}

# ------------------------------------------
#                Miscellaneous
# ------------------------------------------

[misc]
borderstyle = "line"
layout = "Inline" # [Inline, ArtOnTop, StatsOnTop]
stats_margin_top = 0

[misc.figletLogos] # Requires Figlet.
enable = false
color  = "(YW)"
font   = "slant"
margin = [0, 0, 0,]

[misc.imageMode] # Requires Viu.
enable = false
path   = "/path/to/some/image.png" # Please only use absolute paths.
scale  = 18
margin = [2, 2, 3,]
